[workspace]
members = ["psp22", "staking"]
exclude = [".cargo", "target"]
resolver = "2"

[workspace.dependencies]
ink = { version = "5.0.0", default-features = false }
ink_e2e = "5.0.0"
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
